#!/usr/bin/env python
# coding: utf-8

# ### Install requirements

# In[35]:


get_ipython().system('pip install sentence-transformers==4.1.0')
get_ipython().system('pip install requests==2.32.3')
get_ipython().system('pip install matplotlib==3.10.3')
get_ipython().system('pip install openai==1.79.0')
get_ipython().system('pip install langchain-openai==0.3.17')
get_ipython().system('pip install pandas==2.2.3')
get_ipython().system('pip install rank-bm25')
get_ipython().system('pip install langchain_text_*splitters')
get_ipython().system('pip install openai==1.83.0')
get_ipython().system('pip install PyPDF2==3.0.1')


# ### How to generate embeddings using the OpenAI and HuggingFace API

# In[ ]:


from openai import OpenAI

def calculate_embeddings_using_openai():
    """
    Returns:
        embeddings (list): list of embeddings
    """

    from openai import OpenAI

    text_chunks = ["The sky is blue.", "The grass is green."]

    client = OpenAI()  # uses the environment variable OPENAI_API_KEY

    embeddings_list = []

    for text_chunk in text_chunks:
        response = client.embeddings.create(
            input=[text_chunk], model="text-embedding-3-small"
        )
        embedding = response.data[0].embedding
        embeddings_list.append(embedding)


    from langchain_openai import OpenAIEmbeddings

    embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
    embeddings_langchain_list = []

    for text_chunk in text_chunks:
        embeddings_openai_langchain = embeddings.embed_query(text_chunk)
        embeddings_langchain_list.append(embeddings_openai_langchain)

    return embeddings_list, embeddings_langchain_list


# calculate embeddings using openai
embeddings_list, embeddings_langchain_list = (
    calculate_embeddings_using_openai()
)


# In[6]:


print(embeddings_list)
print("Length of embeddings:", len(embeddings_list[0]))

print(embeddings_langchain_list)
print("Length of embeddings:", len(embeddings_langchain_list[0]))


# In[12]:


def create_text_embeddings_using_huggingface():
    '''
    Returns:
        embeddings (list): list of embeddings
    '''
    from sentence_transformers import SentenceTransformer

    # Load the model
    model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    text_chunks = ["The sky is blue.", "The grass is green."]

    # Generate embeddings
    embeddings = model.encode(text_chunks)


    return embeddings

embeddings_huggingface = create_text_embeddings_using_huggingface()


# In[13]:


embeddings_huggingface


# In[ ]:


print(embeddings_huggingface)
print("Length of embeddings:", len(embeddings_huggingface[0]))


# In[9]:


def calculate_embeddings_using_openai():
    """
    Calculates text embeddings using both the OpenAI API and LangChain's OpenAIEmbeddings.

    Returns:
        embeddings_list (list): List of embeddings generated by the OpenAI API for each text chunk.
        embeddings_langchain_list (list): List of embeddings generated by LangChain's OpenAIEmbeddings for each text chunk.
    """
    from openai import OpenAI

    text_chunks = ["The sky is blue.", "The grass is green."]

    client = OpenAI()  # uses the environment variable OPENAI_API_KEY

    embeddings_list = []

    for text_chunk in text_chunks:
        response = client.embeddings.create(
            input=[text_chunk], model="text-embedding-3-small"
        )
        embedding = response.data[0].embedding
        embeddings_list.append(embedding)


    from langchain_openai import OpenAIEmbeddings

    embeddings = OpenAIEmbeddings(model="text-embedding-3-large")
    embeddings_langchain_list = []

    for text_chunk in text_chunks:
        embeddings_openai_langchain = embeddings.embed_query(text_chunk)
        embeddings_langchain_list.append(embeddings_openai_langchain)

    return embeddings_list, embeddings_langchain_list

embeddings_list_openai, embeddings_langchain_list = calculate_embeddings_using_openai()


# In[ ]:


embeddings_list_openai


# In[11]:


embeddings_langchain_list


# ### Calculating the Distance Between Embeddings

# In[ ]:


def calculate_cosine_similarity():
    """
    Calculate the cosine distance between two embeddings using numpy
    and the sentence-transformers library.
    """
    import numpy as np
    from numpy.linalg import norm
    import pandas as pd
    import os
    from openai import OpenAI

    text_chunks = [
        "The Great Fire of London in 1666 destroyed over 13,000 houses.",
        "Julius Caesar was assassinated on the Ides of March (March 15) in 44 BCE.",
        "The Black Death, is estimated to have killed nearly one-third of the \
            population",
    ]

    users_question = "Tell me something interesting about diseases in history"

    embeddings_df = pd.DataFrame(text_chunks, columns=["text_chunk"])

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    embeddings = []

    def create_embeddings(text_chunk, client):
        embedding = (
            client.embeddings.create(input=[text_chunk], model="text-embedding-3-small")
            .data[0]
            .embedding
        )
        return embedding

    # Apply function create_embeddings to the correct column
    embeddings_df["embedding"] = embeddings_df["text_chunk"].apply(
        create_embeddings, client=client
    )

    users_question_embedding = create_embeddings(
        text_chunk=users_question, client=client
    )

    # create a list to store the calculated cosine similarity
    cos_sim = []

    def calculate_cosine_similarity(text_chunk_embedding, users_question_embedding):
        A = text_chunk_embedding
        B = users_question_embedding

        # calculate the cosine similarity
        cosine = np.dot(A, B) / (norm(A) * norm(B))
        return cosine

    # Apply function calculate_cosine_distance to the correct column
    embeddings_df["similarity"] = embeddings_df["embedding"].apply(
        calculate_cosine_similarity, users_question_embedding=users_question_embedding
    )

    return embeddings_df, users_question


# In[15]:


embeddings_df, users_question = calculate_cosine_similarity()


# In[17]:


embeddings_df


# In[ ]:


def calculate_cosine_distance_using_sentence_transformer(document_embeddings, query_embedding):
    """
    Calculate the cosine distance between document embeddings and a query embedding
    using the sentence-transformers library.

    Args:
        document_embeddings (list): List of document embeddings.
        query_embedding (list): Query embedding.

    Returns:
        scores (numpy.ndarray): Cosine similarity scores.
    """
    from sentence_transformers.util import cos_sim

    for document_embedding in document_embeddings:
        # Compute cosine_similarity between documents and query
        scores = cos_sim(document_embedding, query_embedding)
    return scores

scores = calculate_cosine_distance_using_sentence_transformer(
    document_embeddings=embeddings_df["embedding"].tolist(),
    query_embedding=embeddings_df["embedding"].tolist()
)


# In[46]:


scores


# ### How to reduce the dimensionality of embeddings to be able to plot them

# In[ ]:


import sys
import pandas as pd
import os

def create_pca_plot():
    """
    Reduces the dimensionality of text embeddings using PCA and visualizes them in a 2D scatter plot.

    Returns:
        df_reduced (DataFrame): DataFrame containing the reduced 2D coordinates and corresponding text labels.
    """
    import os
    import pandas as pd
    import matplotlib.pyplot as plt
    from sklearn.decomposition import PCA
    from openai import OpenAI

    # Define text chunks
    text_chunks = [
        "The sky is blue.",
        "The sun is shining.",
        "I love chocolate.",
        "Ice cream is delicious.",
        "Roses are red.",
        "Violets are blue.",
    ]

    # Initialize OpenAI client
    client = OpenAI()  # uses the environment variable OPENAI_API_KEY
    embeddings = []

    # Generate embeddings for text chunks
    for text_chunk in text_chunks:
        response = client.embeddings.create(
            input=[text_chunk], model="text-embedding-3-small"
        )
        embedding = response.data[0].embedding
        embeddings.append(embedding)

    # Convert embeddings to a DataFrame
    embeddings_df = pd.DataFrame(
        embeddings, columns=[f"dim_{i}" for i in range(len(embeddings[0]))]
    )

    # Perform PCA with 2 components
    pca = PCA(n_components=2)
    df_reduced = pca.fit_transform(embeddings_df)

    # Create a new DataFrame with reduced dimensions
    df_reduced = pd.DataFrame(df_reduced, columns=["PC1", "PC2"])
    df_reduced["text"] = text_chunks  # Add original text chunks for labeling

    # Function to create a scatter plot
    plt.figure(figsize=(8, 6))
    plt.scatter(df_reduced["PC1"], df_reduced["PC2"])

    # Add labels to each point
    for i, label in enumerate(df_reduced["text"]):
        plt.text(df_reduced["PC1"][i], df_reduced["PC2"][i], label, fontsize=9)

    # Add labels and title
    plt.xlabel("Principal Component 1")
    plt.ylabel("Principal Component 2")
    plt.title("PCA Scatter Plot")

    # Save the plot
    plt.savefig("../results/principal_component_plot.svg", format="svg")
    return plt, df_reduced

plt = create_pca_plot()


# ### How to calculate the distance and similarity of embeddings

# ### How to calculate multimodal embeddings using CLIP

# In[ ]:


def create_embeddings_using_clip():
    import torch
    from PIL import Image
    from transformers import CLIPProcessor, CLIPModel

    # Load the model and processor
    model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
    processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

    # Text and image inputs
    descriptions = ["A photo of a cat", "A photo of a dog"]
    images = [
        Image.open("../datasets/images/cat.jpg"),
        Image.open("../datasets/images/dog.jpg"),
    ]

    # Inference
    with torch.no_grad():
        inputs = processor(
            text=descriptions,
            images=images,
            return_tensors="pt",
            padding=True,
            truncation=True,
        )
        outputs = model(**inputs)

    dot_products_per_text = outputs.logits_per_text

    # Calculate probabilities
    probabilities = dot_products_per_text.softmax(dim=1)

    return probabilities, dot_products_per_text



# In[22]:


probabilities, dot_products_per_text = create_embeddings_using_clip()


# In[ ]:


print(probabilities)

print("Probability that the first image is a cat:", probabilities[0][0].item())
print("Probability that the second image is a dog:", probabilities[1][1].item())


# ### How to use embeddings to train text classification models

# In[ ]:


import sys
import pandas as pd
import os

def hybrid_search():
    """
    This function is used in chapter 3: Embeddings for the
    recipe hybrid search. It is combining keyword search using the
    BM25 algorithm and semantic search using embedding models and
    cosine similarity.
    """
    # bm25 keyword search algorithm
    from rank_bm25 import BM25Okapi

    text_chunks = [
        "The Great Fire of London in 1666 destroyed over 13,000 houses.",
        "Julius Caesar was assassinated on the Ides of March (March 15) in 44 BCE.",
        """The Black Death, is estimated to have killed nearly one-third of the European
        population""",
    ]
    tokenized_chunks = [chunk.split(" ") for chunk in text_chunks]

    bm25 = BM25Okapi(tokenized_chunks)

    users_query = "Tell me something interesting about diseases in history"
    tokenized_query = users_query.split(" ")

    doc_scores = bm25.get_scores(tokenized_query)

    ranking_keyword_search = (
        pd.DataFrame(doc_scores, columns=["scores"])
        .sort_values(by="scores", ascending=False)
        .index.to_list()
    )

    from sentence_transformers.util import cos_sim

    embeddings_df = pd.DataFrame(text_chunks, columns=["text_chunk"])

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    embeddings = []

    def create_embeddings(text_chunk, client):
        embedding = (
            client.embeddings.create(input=[text_chunk], model="text-embedding-3-small")
            .data[0]
            .embedding
        )
        return embedding

    embeddings_df["embedding"] = embeddings_df["text_chunk"].apply(
        create_embeddings, client=client
    )

    users_question_embedding = create_embeddings(text_chunk=users_query, client=client)

    # Compute cosine_similarity between documents and query
    embeddings_df["similarity"] = cos_sim(
        embeddings_df["embedding"], users_question_embedding
    )

    ranking_semantic_search = embeddings_df.sort_values(
        by=["similarity"], ascending=False
    ).index

    return ranking_semantic_search, ranking_keyword_search


# In[ ]:


ranking_semantic_search, ranking_keyword_search = hybrid_search()


# In[ ]:


def calculate_hybrid_search_score(ranking_semantic_search, ranking_keyword_search):
    #  calculate a combined similarity score using Reciprocal Rank Fusion (RRF)
    combined_score = []

    for i in range(0, len(ranking_semantic_search), 1):
        k = 60
        rrf_score = 1 / (k + ranking_keyword_search[i]) + 1 / (
            k + ranking_semantic_search[i]
        )
        combined_score.append(rrf_score)

    combined_score_df = pd.DataFrame(combined_score, columns=["combined_score"])
    new_ranking = (
        combined_score_df.sort_values(by=["combined_score"], ascending=False).index + 1
    )


    return new_ranking


# In[ ]:


new_ranking = calculate_hybrid_search_score(
    ranking_semantic_search, ranking_keyword_search
)


# ### How to optimize similarity search by combining similarity search and keyword search

# In[ ]:


def hybrid_search():
    """
    This function is used in chapter 3: Embeddings for the
    recipe hybrid search. It is combining keyword search using the
    BM25 algorithm and semantic search using embedding models and
    cosine similarity.
    """
    # bm25 keyword search algorithm
    from rank_bm25 import BM25Okapi
    import pandas as pd
    import os

    text_chunks = [
        "The Great Fire of London in 1666 destroyed over 13,000 houses.",
        "Julius Caesar was assassinated on the Ides of March (March 15) in 44 BCE.",
        """The Black Death, is estimated to have killed nearly one-third of the European
        population""",
    ]
    tokenized_chunks = [chunk.split(" ") for chunk in text_chunks]

    bm25 = BM25Okapi(tokenized_chunks)

    users_query = "Tell me something interesting about diseases in history"
    tokenized_query = users_query.split(" ")

    doc_scores = bm25.get_scores(tokenized_query)

    ranking_keyword_search = (
        pd.DataFrame(doc_scores, columns=["scores"])
        .sort_values(by="scores", ascending=False)
        .index.to_list()
    )

    from sentence_transformers.util import cos_sim

    embeddings_df = pd.DataFrame(text_chunks, columns=["text_chunk"])

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    embeddings = []

    def create_embeddings(text_chunk, client):
        embedding = (
            client.embeddings.create(input=[text_chunk], model="text-embedding-3-small")
            .data[0]
            .embedding
        )
        return embedding

    embeddings_df["embedding"] = embeddings_df["text_chunk"].apply(
        create_embeddings, client=client
    )

    users_question_embedding = create_embeddings(text_chunk=users_query, client=client)

    # Compute cosine_similarity between documents and query
    embeddings_df["similarity"] = cos_sim(
        embeddings_df["embedding"], users_question_embedding
    )

    ranking_semantic_search = embeddings_df.sort_values(
        by=["similarity"], ascending=False
    ).index

    return ranking_semantic_search, ranking_keyword_search


# In[ ]:


ranking_semantic_search, ranking_keyword_search = hybrid_search()


# In[ ]:


def calculate_hybrid_search_score(ranking_semantic_search, ranking_keyword_search):
    #  calculate a combined similarity score using Reciprocal Rank Fusion (RRF)
    combined_score = []

    for i in range(0, len(ranking_semantic_search), 1):
        k = 60
        rrf_score = 1 / (k + ranking_keyword_search[i]) + 1 / (
            k + ranking_semantic_search[i]
        )
        combined_score.append(rrf_score)

    combined_score_df = pd.DataFrame(combined_score, columns=["combined_score"])
    new_ranking = (
        combined_score_df.sort_values(by=["combined_score"], ascending=False).index + 1
    )


    return new_ranking


# In[ ]:


calculate_hybrid_search_score(
    ranking_semantic_search, ranking_keyword_search
)


# ### Performing Text Classification Using Embeddings

# In[36]:


def load_football_and_deep_learning_history():
    # read some sample documents and split it into chunks
    from langchain_text_splitters import RecursiveCharacterTextSplitter
    import PyPDF2
    import pandas as pd
    import os
    from openai import OpenAI

    pdf_files = [
        {
            "file_path": "../datasets/pdf_files/history_of_deep_learning.pdf",
            "label": "Deep_Learning",
        },
        {
            "file_path": "../datasets/pdf_files/premier_league_history.pdf",
            "label": "Premier_League",
        },
    ]

    chunks_dict_list = []

    # split both documents into chunks and append to the same list of dicts
    for pdf_file in pdf_files:
        with open(pdf_file["file_path"], "rb") as file:
            reader = PyPDF2.PdfReader(file)

            text = ""
            for page in reader.pages:
                text += page.extract_text()

        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=200,
            chunk_overlap=0,
            length_function=len,
            is_separator_regex=False,
        )

        chunks = text_splitter.split_text(text)

        for chunk in chunks:
            chunks_dict_list.append({"text": chunk, "label": pdf_file["label"]})

    chunks_df = pd.DataFrame(chunks_dict_list)

    client = OpenAI()  # uses the environment variable OPENAI_API_KEY

    def create_embeddings(text_chunk, client):
        response = client.embeddings.create(
            input=[text_chunk], model="text-embedding-3-small"
        )
        embedding = response.data[0].embedding
        return embedding

    chunks_df["embedding"] = chunks_df["text"].apply(create_embeddings, client=client)
    chunks_df.to_csv("chunks_df.csv")

    return chunks_df

chunks_df = load_football_and_deep_learning_history()


# In[37]:


chunks_df


# In[44]:


def building_a_classification_model_using_embeddings(chunks_df):
    from openai import OpenAI
    import os
    import pandas as pd

    def create_embeddings(text_chunk, client):
        embedding = (
            client.embeddings.create(input=[text_chunk], model="text-embedding-3-small")
            .data[0]
            .embedding
        )
        return embedding

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    from sklearn.ensemble import RandomForestClassifier
    from sklearn.datasets import make_classification

    y = chunks_df["label"]
    X = chunks_df["embedding"].apply(
        lambda x: pd.Series(eval(x)) if isinstance(x, str) else pd.Series(x)
    )

    # Train a random forest classifier
    clf = RandomForestClassifier()
    clf.fit(X, y)


    # Predict probabilities
    test_embedding = create_embeddings(
        text_chunk="What is the name of the top football league in England?",
        client=client,
    )

    X_test = [test_embedding]

    # Predict the most likely class
    predicted_classes = clf.predict(X_test)  # e.g. ['Premier_League']
    probabilities = clf.predict_proba(X_test)  # e.g. array([[0.06, 0.94]])

    return predicted_classes, probabilities


# In[45]:


predicted_classes, probabilities = building_a_classification_model_using_embeddings(chunks_df)


# In[48]:


predicted_classes, probabilities


# In[ ]:




